name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use an Ubuntu runner for the job

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3 # Checkout the repository to the runner

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.138.0" # Specify Hugo version here

      - name: Cache Hugo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/hugo
            public/
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/*.md', '**/*.html', '**/*.css', '**/*.js') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Run Hugo to generate the site
        run: hugo # Run Hugo to generate the static site

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"  # Configure git user for commits

      - name: Add changes and commit
        run: |
          git add .  # Add changes to Git
          git diff --cached --quiet || git commit -m "Added article"  # Commit changes, if any
        continue-on-error: true # Ignore errors if no changes are detected

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Use the peaceiris GH Pages deploy action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token for authentication
          target_branch: gh-pages # Target branch for deployment
          source_dir: public # Directory to push to GitHub Pages (generated by Hugo)
